# Generated by Django 6.0.3 on 2026-03-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_url', models.URLField(unique=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('reviews', models.PositiveIntegerField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('appointment_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_full', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo_url_full', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='parser_app.doctor')),
            ],
            options={
                'db_table': 'doctor_gallery',
            },
        ),
    ]
