# Generated by Django 5.2.5 on 2026-04-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address_full',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='appointment_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url_full',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='website',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='doctorgallery',
            name='photo_url',
            field=models.URLField(max_length=2000),
        ),
    ]
