# Generated by Django 5.2.5 on 2026-04-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_doctor_address_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='search_slug',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('profile_url', 'search_slug')},
        ),
    ]
